### ISSUE TITLE
Issue with arabic seller name

### ISSUE THREAD

**Issue by Mehdi-android** [iabdelgawaad/Zatca#1]
Hi, I have used your code to fulfil the zatca. There is one problem if the seller name is Arabic then QR code is not able to scan and it says QR is not compatible with Zakat, Tax and Custom Authority.

**Comment by iabdelgawaad** [comment]
This will fix the issue:
value.toByteArray()?.size?.toString()

Apply on the 5 values

**Comment by iabdelgawaad** [comment]
Also try to use this builder

ZatcaQRCodeGeneration.Builder()

**Comment by iabdelgawaad** [comment]
![photo_2021-11-30_21-07-38](https://user-images.githubusercontent.com/4660684/144844425-de25251a-da94-4794-8e1c-15b255ab07b8.jpg)
###
