### ISSUE TITLE
What is the separation chars between the content items ?

### ISSUE THREAD

**Issue by tamkeen-tms** [iabdelgawaad/Zatca#2]
I tried to decode the "AQ1TaGF3cm1hIEhvdXNlAgoxMjM0NTY3ODkwAxMyMi8xMS8yMDIxIDAzOjAwIGFtBAMxMDAFAjE1" string, and the data shows, but is separated by a character that is not identified, what is it?!

![Base64 Decode - Online Tool 12-27-2021 10-36-13 PM](https://user-images.githubusercontent.com/13228056/147505646-7da00073-c168-48de-b2c9-1fdebf053f27.png)

Thanks

**Comment by iabdelgawaad** [comment]
That's the expected output for ZATCA 

Check some other outputs from different platforms like Salla:
https://salla.dev/blog/qr-code-fatoora-e-invoicing-zatca/

**Comment by iabdelgawaad** [comment]
The identified characters is the tag and length encoding: 
https://github.com/iabdelgawaad/ZATCA#:~:text=By%20Creating%20a%20TLV%20Byte%20Array%20for%20field%20like%20this%3A

**Comment by tamkeen-tms** [comment]
Ah, thanks.
