### ISSUE TITLE
Not able to scan the QR code.

### ISSUE THREAD

**Issue by Mehdi-android** [iabdelgawaad/Zatca#3]
I received an email from ZATCA that they are not able to scan the QR code generated by your code. They scanned with this app https://play.google.com/store/apps/details?id=com.zatca.vat

**Comment by iabdelgawaad** [comment]
Yes, I've add some fixes regarding this issue and I will push soon.

**Comment by iabdelgawaad** [comment]
Just for now

Try to 

1.  use this date format "yyyy-MM-dd HH:mm:ss" before sending to 
`InvoiceDate("date after format"),`

2. trim any new line after encoding replace this line 

`return Base64.encodeToString(tlvs, Base64.DEFAULT) ` 

with 
 ```
 var text = Base64.encodeToString(tlvs, Base64.DEFAULT)
            return text.replace("\n", "")
```

**Comment by Mehdi-android** [comment]
It Worked thanks

**Comment by iabdelgawaad** [comment]
Enjoy coding :)
