### ISSUE TITLE
ZATCA 2nd Phase QR

### ISSUE THREAD

**Issue by Harisul44** [iabdelgawaad/Zatca#4]
We want to integrate zatca 2nd phase QR. Can you help us?

**Comment by iabdelgawaad** [comment]
How can I help you? Do you want it to be implemented in your Android app?

**Comment by Harisul44** [comment]
We want implement in Windows application and also android. If you create a api for all then it will be best.

**Comment by iabdelgawaad** [comment]
API for which platform?

**Comment by Harisul44** [comment]
Windows application C# .net.

**Comment by iabdelgawaad** [comment]
contact me through this email: iabdelgawaad@gmail.com

**Comment by Harisul44** [comment]
I have send email to you. Please review.
